name: publish

on:
  push:
    braches: ['release']

jobs:
  publish-marcos-22nd-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build the marcos-22nd Docker image
      run: |
        docker build . --build-arg GITHUB_PAT=${{ secrets.DOCKERFILE_TOKEN }} --tag ghcr.io/anshulkamath/marcos-22nd:latest
        docker run ghcr.io/anshulkamath/marcos-22nd:latest
        docker push ghcr.io/anshulkamath/marcos-22nd:latest
